### ISSUE TITLE
error during container creation

### ISSUE THREAD

**Issue by danilaplee** [gonzalolarralde/swifty-robot-environment#3]
Hi! I'am getting this error:

Applying apple/swift#6488 from to swift: Closed or not mergeable...
Applying apple/swift-corelibs-libdispatch#197 from to swift-corelibs-libdispatch: Closed or not mergeable...
Applying apple/swift-corelibs-foundation#758 from to swift-corelibs-foundation: Closed or not mergeable...
Applying apple/swift#7773 from to swift: Closed or not mergeable...
Applying apple/swift#7777 from to swift: Closed or not mergeable...
Applying apple/swift-corelibs-libdispatch#228 from to swift-corelibs-libdispatch: Closed or not mergeable...
**Applying gonzalolarralde/swift#2 from to swift: error: patch failed: cmake/modules/AddSwift.cmake:359
error: cmake/modules/AddSwift.cmake: patch does not apply
error: patch failed: cmake/modules/AddSwift.cmake:359
error: cmake/modules/AddSwift.cmake: patch does not apply
error: patch failed: stdlib/public/SwiftShims/LibcShims.h:113
error: stdlib/public/SwiftShims/LibcShims.h: patch does not apply
error: patch failed: cmake/modules/AddSwift.cmake:1505
error: cmake/modules/AddSwift.cmake: patch does not apply**

**Comment by JohanDufau** [comment]
Hello,

To bypass this error, just adapt the script 040_clone_last_swift.sh by removing the patch in error:
```
export APPROVED_PRS_URL=https://gist.githubusercontent.com/JohanDufau/46b6c7841b9b67b5e574f8dbde024563/raw/1cc20df7ba24beb9b9bbb980ac464daa074c7945/Swift%2520PR
```

It removes this PR: gonzalolarralde swift 2.

I'm reviewing each PR and I'll let you know why this PR is not working + submit a new one to totally fix this.

**Comment by gonzalolarralde** [comment]
ok I just fixed that PR. It was overlapping with @johnno1962 's fixes. I'll give it a run now. Thanks @JohanDufau for the workaround.

**Comment by gonzalolarralde** [comment]
They just removed the dependency so this shouldn't be a problem anymore. Check apple/swift-corelibs-libdispatch#277 for further reference.
