### ISSUE TITLE
issue during compiling of corelibs_libdispatch

### ISSUE THREAD

**Issue by danilaplee** [gonzalolarralde/swifty-robot-environment#4]
make[2]: Entering directory '/root/swift-source/swift-corelibs-libdispatch/src'
/bin/bash ../libtool  --tag=CC   --mode=compile /root/swift-source/build/Ninja-ReleaseAssert/llvm-linux-x86_64/bin/clang -DHAVE_CONFIG_H -I. -I../config  -I.. -I.. -I../private -DDISPATCH_USE_DTRACE=0  -Wall -fvisibility=hidden -momit-leaf-frame-pointer    -fblocks -I../src/BlocksRuntime -O2 -target arm-linux-androideabi --sysroot=/root/ndk/android-ndk-r14b/platforms/android-21/arch-arm -B/root/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin -c -o allocator.lo allocator.c
libtool: compile:  /root/swift-source/build/Ninja-ReleaseAssert/llvm-linux-x86_64/bin/clang -DHAVE_CONFIG_H -I. -I../config -I.. -I.. -I../private -DDISPATCH_USE_DTRACE=0 -Wall -fvisibility=hidden -momit-leaf-frame-pointer -fblocks -I../src/BlocksRuntime -O2 -target arm-linux-androideabi --sysroot=/root/ndk/android-ndk-r14b/platforms/android-21/arch-arm -B/root/ndk/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin -c allocator.c  -fPIC -DPIC -o .libs/allocator.o
In file included from allocator.c:21:
In file included from ./internal.h:633:
In file included from ./shims.h:175:
./shims/lock.h:63:10: fatal error: 'linux/membarrier.h' file not found
#include <linux/membarrier.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:695: recipe for target 'allocator.lo' failed
make[2]: Leaving directory '/root/swift-source/swift-corelibs-libdispatch/src'
make[2]: *** [allocator.lo] Error 1
Makefile:546: recipe for target 'all' failed
make[1]: Leaving directory '/root/swift-source/swift-corelibs-libdispatch/src'
make[1]: *** [all] Error 2
Makefile:454: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
The command '/bin/sh -c /bin/bash -e 060_build_corelibs_libdispatch.sh' returned a non-zero code: 2

**Comment by gonzalolarralde** [comment]
Shouldn't be a problem now that the dependency has been removed. Check apple/swift-corelibs-libdispatch#277
